name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docs
        run: sh ./build.sh
        shell: sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-v6
          path: dist/v6/site

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-v7
          path: dist/v7/site
