name: CI

on:
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: build docs
        run: sh ./build.sh
        shell: sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-v6
          path: dist/v6/site

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-v7
          path: dist/v7/site
          
      - name: Publish v6
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist/v6/site
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_v6 }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
#       - name: Publish v7
#         uses: netlify/actions/cli@master
#         with:
#           args: deploy --dir=dist/v7/site
#         env:
#           NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_v7 }}
#           NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
